PredictionModel:
  - name: "InfiGUI-R1-3B"
    model_path: "models/InfiGUI-R1-3B"
  - name: "Qwen2.5-VL-3B-UI-R1"
    model_path: "models/Qwen2.5-VL-3B-UI-R1"
  - name: "OS-Atlas-Base-7B"
    model_path: "models/OS-Atlas-Base-7B"
  - name: "OS-Atlas-Base-4B"
    model_path: "models/OS-Atlas-Base-4B"
  - name: "Qwen2.5-VL-3B-UI-R1-E"
    model_path: "models/Qwen2.5-VL-3B-UI-R1-E"
  - name: "UGround-V1-7B"
    model_path: "models/UGround-V1-7B"
  - name: "Jedi-3B-1080p"
    model_path: "models/Jedi-3B-1080p"
  - name: "Jedi-7B-1080p"
    model_path: "models/Jedi-7B-1080p"
